### ISSUE TITLE
"Styraconyx" release checklist

### ISSUE THREAD

**Issue by cwgoes** [cryptiumlabs/juvix#112]
- [ ] Functional LLVM backend (interaction net evaluator, simple bespoke encoding) - @mariari 
- [x] Complete core typechecker & evaluator for dependently-typed lambda calculus - @thealmarty 
- [x] Core erasure to elementary affine core, erased core @cwgoes 
- [ ] Complete argument for correctness of abstract algorithm + read-back @mariari @cwgoes 
- [ ] ~Some form of usage polymorphism? @andy-morris~ (next release)
- [x] Natural numbers in core @thealmarty

**Comment by cwgoes** [comment]
Core grammar that should be supported in this release:

```
R, S, T, s, t ::= ∗_i | Natural | π x : S -> T | λx . t | e

d, e, f ::= x | 0, 1, 2 (natural constant) | f s | π s : S
```

**Comment by cwgoes** [comment]
Further to-do for core in this release:
- Abstract term over binder type (for both de Bruijin indices & names)
- Add abstracted-over provision for "built-in" functions per language reference
- Clean up syntax a bit (with named variables) so it's easier to write
- Add lots of testcases (preferably in nice syntax)
- Pass through type information to erasure step
- Run full erasure algorithm as described in language reference

**Comment by cwgoes** [comment]
Additional core tasks:
- [ ] Primitive functions (addition, subtraction, etc.) over naturals - @cwgoes 
- [ ] More test-cases, particularly of typechecker (SKI combinators, see Agda code) - @thealmarty 
- [ ] Parameterise core over Michelson backend - @cwgoes 
- [ ] Example (simple) core contracts with proofs that compile to Michelson - @thealmarty

**Comment by cwgoes** [comment]
Target date: 15 November.

**Comment by cwgoes** [comment]
Blocked on:
- https://github.com/cryptiumlabs/juvix/pull/180
- https://github.com/cryptiumlabs/juvix/pull/185
- https://github.com/cryptiumlabs/juvix/pull/187
- https://github.com/cryptiumlabs/juvix/pull/173

**Comment by cwgoes** [comment]
Done - https://github.com/cryptiumlabs/juvix/releases/tag/styraconyx

See next release: https://github.com/cryptiumlabs/juvix/issues/186
