### ISSUE TITLE
Pseudobiotus release task-list

### ISSUE THREAD

**Issue by cwgoes** [cryptiumlabs/juvix#283]
Proposed task-list. Release date: 10 February 2020.

- [x] Extensible core syntax with TTG & Template Haskell (https://github.com/cryptiumlabs/juvix/issues/299) (@andy-morris)
- [ ] Full core pass-through to Michelson backend, including annotations (@cwgoes following #299)
- [ ] Additional tests & optimisations for Michelson backend (@cwgoes @mariari)
      - Push/enter
      - Constant propagation
- [ ] Detailed design of frontend language syntax & semantics (all - ref https://github.com/cryptiumlabs/juvix/issues/273 and https://github.com/cryptiumlabs/juvix/pull/284)
- [ ] Continued research into proof UX w/Idris, Agda, Coq, F* (ref https://github.com/cryptiumlabs/juvix/issues/139#issuecomment-568546250) (@thealmarty)

**Comment by cwgoes** [comment]
Done - https://github.com/cryptiumlabs/juvix/releases/tag/pseudobiotus.
