### ISSUE TITLE
Hooking things up

### ISSUE THREAD

**Issue by cwgoes** [cryptiumlabs/juvix#333]
- [x] Basic frontend AST per latest spec in language reference
- [ ] Simple conversion to core without unification or implicit variables or case expressions (yet)
- [ ] Type-checked core => annotated core (ref https://github.com/cryptiumlabs/juvix/issues/265)
- [x] Clean up erasure (ref https://github.com/cryptiumlabs/juvix/issues/190)
- [ ] Erased core => Michelson
- [ ] Unify the logging monad stack a bit for easier debugging
- [ ] Alter parameterisation (ref https://github.com/cryptiumlabs/juvix/issues/326)

**Comment by cwgoes** [comment]
Closing in favour of https://github.com/cryptiumlabs/juvix/issues/352.
