### ISSUE TITLE
Juvix "Turtle" release strategy

### ISSUE THREAD

**Issue by cwgoes** [cryptiumlabs/juvix#56]
"Slow and steady wins the race."

- [x] Write basic REPL - https://github.com/cryptiumlabs/juvix/issues/43 @cwgoes 
- [x] Add Core-to-EAL erasure @cwgoes 
- [ ] Finish MVP core syntax, semantics - https://github.com/cryptiumlabs/juvix/issues/47 @thealmarty @cwgoes 
- [x] Finish section on Mendler, Scott encodings in the language reference - @mariari 
- [x] Add read-back from interaction nets to BOHM or EAL terms - @mariari 
- [ ] Debug EAL inference algorithm - @mariari @cwgoes 
- [x] Investigate sub-usaging, add Agda code to directory in repository & section to language reference - https://github.com/cryptiumlabs/juvix/issues/46 @andy-morris, review by all
- [ ] Open-source the project on August 28th
- [ ] Circulate to our contacts, especially Victor Maia (Formality), type theory researchers
- [ ] (a few weeks after) Explain the aims & strategy of the project in a few blog posts

The MVP release will not be ready for production (or even experimental) use, but should provide a reasonable idea to readers of the aims and strategy of the project, and further development work can proceed in public, which is helpful for transparency and inclusion of interested parties.

**Comment by cwgoes** [comment]
Open-sourced; work on Core, typechecking, erasure, etc. will continue unabated.
